### ISSUE TITLE
上传功能不可用

### ISSUE THREAD

**Issue by fantastlcok** [VGEAREN/pikpak-webdav#3]
**描述：**
上传功能不可用，可正常列出目录。

**复现：**
上传文件到webdav

**预期：**
文件上传至PikPak

**截图：**

**环境：**
 - Docker
 - 2021-12-14

**运行参数：**

```
version: '3'
services:
  pikpak-webdav:
    image: vgearen/pikpak-webdav
    container_name: pikpak-webdav
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
    network_mode: "host" # 使用宿主机的代理
    tty: true
    environment:
      - TZ=Asia/Shanghai
      - "PIKPAK_USERNAME=email"
      - "PIKPAK_PASSWORD=pass"
      #- PIKPAK_PROXY_HOST=<change me>
      #- PIKPAK_PROXY_PORT=<change me>
      #- PIKPAK_PROXY_PROXY-TYPE=<change me>
      - SERVER_PORT=15499
      # - PIKPAK_AUTH_USER_NAME=<change me>
      # - PIKPAK_AUTH_PASSWORD=<change me>
```
